### ISSUE TITLE
subject is based on the ldap dn, which is neither stable, nor non-reassignable

### ISSUE THREAD

**Issue by butonic** [Kopano-dev/konnect#3]
AFAICT the OIDC subject claim is based on the distinguished name of an ldap user. But distinguished names are subject to change when
- the rdn, eg. `cn` or `uid` changes because of marriage, divorce or the ldap admin deciding to move from U123456 style `cn`s to firstname.lastname style (yep we had that)
- the user moves to a different group
- a rename happens, eg. to prevent collisions when merging user trees (eg. due to company merger)

BTW: `uid`, `cn` or `samaccountname` are not unique because they may collide in a multi domain environment. And they are subject to change.

The next best thing is the LDAP server specific uuid attribute (openldap has `entryuuid`, active directory has `objectguid`, [more exist](https://github.com/owncloud/user_ldap/blob/aa0362a0ce7e73157ef830a4c803ca70fc9f279b/lib/Access.php#L1628-L1651)) which is randomly generated when an ldap node is created.

Unfortunately, a savvy admin might decide to copy a user to a different node, eg. to perform batch renames. In that case a new uuid is generated. Which is why AD recommends using the `objectSID` (security identifiers) over the `objectguid`. While it will change, even when the user is moved (not copied) around, old `objectSID` entries are kept in the `sIDHistory` attribute of the user, see the [ms docs](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc961625(v=technet.10)) for details.

The NTFS filesystem stores permissions based on the sid of a user, because even when it changes the user can still be looked up by matching the sid against the objectsid AND the sid-history attribute.

ownCloud tries to find a user dn based on whatever login attribute was configured. It keeps track of the users dn, the uuid and a generated internal ownCloud username for that user. The code allows changes of the dn because it will fallback to a uuid based search and update the dn in the mapping table if it changed. We currently recommend to use the uuid attribute as the internal username because we wrongly assumed it would be stable ... until we ran into that admin that copied all users. Actually, the internal username will never be updated to prevent data loss, but now the uuid in ldap and the owncloud username no longer match, which is confusing and makes debugging unnecessary hard.

That being said, what can be done, when you are facing the same problem?
For AD you can store and lookup the users subject claim based on the objectsid / sid-history values. 
Unfortunately, openldap does not have something like a `enryuuidhistory` attribute (or I am not aware of it), otherwise you could identify the user based on the `sIDHistory`. The onlyIdea I have is documenting a recommendation to let the admin generate a real stable non-reassignable uuid attribute. :man_shrugging: 

Maybe the [SCIM](http://www.simplecloud.info/) rfcs define a schema and attribute for the [SCIM id](https://ldapwiki.com/wiki/SCIM%20id) that can be added to an openldap ad, but I havent found it.

Maybe it makes more sense to separate the problem and implement a SCIM backend. Then the actual scim id to ldap user mapping is the problem of another service. Ad if you already have a SCIM in place yo can use that (see http://www.simplecloud.info/#Implementations2 for a list of implementations)

Opinions?

**Comment by longsleep** [comment]
This is great thanks for adding us into the loop. You are right, currently the Konnect LDAP backend uses the LDAP DN to derive the public subject of users. 

This behavior currently hardcoded at https://github.com/Kopano-dev/konnect/blob/fe2437fa82c3a73f6e56c1ac7248aa473fff95ef/identifier/backends/ldap.go#L147 which then gets transformed to a public subject in https://github.com/Kopano-dev/konnect/blob/fe2437fa82c3a73f6e56c1ac7248aa473fff95ef/identity/managers/identifier.go#L63.

So for the reasons you stated, it is clear that there is no general answer to this problem. 

On my short term list for Konnect is to make this a configuration and to further increase the likeliness that a sufficiently unique and unchanging subject can be derived, i propose to support configuration of two fields which if set will be used both as internal subject. 

That way it becomes possible to use not globally unique id fields like uid or samaccountname together with an additional field like (o). Also when this can be configured, it also becomes possible to use other fields an specific ldap tree might have for unique user identification. We just need a way to serialize these fields into the access token claims, since we need the values again to lookup the user from LDAP for example for the userinfo requests.

This leaves the case where literally all fields identifying a user get changed. I do not see how this can be handled (like admin recreating all users from meta data but without keeping existing ids). This means that in some cases the ID token subject might change even if it is the same user. If that is a problem or not, depends on the relying parties exact implementation. A RP which knows about Konnect access tokens, might find additional information to do its own mapping/updating in kc.identiy claims.

**Comment by longsleep** [comment]
First commit has landed. I still want to look into AD use cases to figure out if it might make sense to add a special mode to derive from the first value in `sIDHistory` and other binary fields.

**Comment by longsleep** [comment]
AD is not very feasible - closing this for now, to be done later when a real use case for special modes with `sIDHistory` or similar might arise.
